### ISSUE TITLE
请问这个demo只支付微信支付吗，支付宝支持吗

### ISSUE THREAD

**Issue by alasai** [PingPlusPlus/pingpp-csharp#9]
请问这个demo只支付微信支付吗，支付宝支持吗

**Comment by michealzh** [comment]
支持的 https://github.com/PingPlusPlus/pingpp-csharp/blob/master/Example/Example/ChargeDemo.cs#L17 如果是客户端支付需要接入相应的iOS或者Android的 SDK就可以了
